### ISSUE TITLE
Background commands not work for this case

### ISSUE THREAD

**Issue by hellosimple** [trntv/yii2-command-bus#16]
Hi,

I follow the readme "2. Background commands support (optional)"

ReportCommand:
`class ReportCommand extends Object implements BackgroundCommand, SelfHandlingCommand
{
    use BackgroundCommandTrait;

```
public $someImportantData;

public function handle($command) {
    // do what you need
    // echo 'handle command';
    $m = new TimelineEvent();
    $m->application = 'application';
    $m->category = 'test';
    $m->event = 'test';
    $m->data = json_encode(['k'=>'v'], JSON_UNESCAPED_UNICODE);
    $r = $m->save(false);
    return $r;
}
```

}`

Controller:
`$process = Yii::$app->commandBus->handle(new ReportCommand([
            'async' => true,
            'someImportantData' => [],
        ]));
        sleep(5); // Notice this line
`

If use sleep here, it will work(a new record in DB). If not use sleep, it will not work(I can't find new record in DB). What's the difference？
Need your help, thank you!

**Comment by comradefuzz** [comment]
I guess that's because of symfony's Process component when running async is using `proc_open`. That means that if master process ends all of it's child processes will be killed too. 
In this case I suggest using `exec("{$binary} {$binaryArguments} {$path} {$route} {$arguments} &")` instead of `$process->start()` (see [CommandMiddleware](https://github.com/trntv/yii2-command-bus/blob/c35415c816c1771bc783a58a7970dd78830a595a/src/middlewares/BackgroundCommandMiddleware.php#L82-L84)). Ampersand allows to run system command in detached mode so master process cannot affect it even when stops or being killed.

**Comment by chebureque** [comment]
One way you can run those processes in background is to configure background middleware like this:

```
'commandBus' => [
    'class' => 'trntv\bus\CommandBus',
    'middlewares' => [
        [
            'class' => '\trntv\bus\middlewares\BackgroundCommandMiddleware',
            'backgroundHandlerBinary' => '/usr/bin/php',
            'backgroundHandlerPath' => '@app/yii',
            'backgroundHandlerRoute' => 'background-bus/handle',
            'backgroundHandlerArguments' => ['&']
        ]
    ]
]
```

In my case that helped to run commands in background from both web and console apps.

**Comment by hellosimple** [comment]
I use comradefuzz's solution, using exec("{$binary} {$binaryArguments} {$path} {$route} {$arguments} &") instead of $process->start(), work for me.
 Thanks all of you! Great help for me!
